title: A Mind for Language
show_downloads: false
google_analytics:
theme: 
url: "http://amindforlanguage.com"
collections:
  courses:
    output: true
    permalink: /:collection/:name
  greek:
    output: true
    permalink: /:collection/:name
