baseURL = '/'
languageCode = 'en-us'
title = 'A Mind for Language'
theme = "cogito"
publishDir = "docs"

[params]
# css = ["css/custom.css"]
description = "Hi, I'm Fletcher, avowed Greek nerd.  Here you'll find my thougths on Ancient Greek, language learning, and Pythony things. On, and resoruces to help make learning Greek easier."
mainSection = "posts"
mainSectionTitle = "Blog"
showAllPostsOnHomePage = true 
postsOnHomePage = 10 
tagsOverview = false 
tocInline = true
showProjectsList = true
projectsUrl = "https://github.com/fhardison"


[[params.social]]
  name = "github"
  link = "https://github.com/fhardison"

[[params.social]]
  name = "twitter"
  link = "https://github.com/fhardison"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4
